package NPT.NptPageObjects.NptPageUIs;

public class NptProductPageUI {
    public static final String MANAGE_PRODUCT = "//p[text()='Quản lý sản phẩm']";
    public static final String CREATE_PRODUCT_BUTTON = "//button[contains(text(),'Tạo sản phẩm')]";
    public static final String BARCODE_FIELD = "//input[@placeholder='Nhập mã vạch']";
    public static final String PRODUCT_NAME_FIELD = "//input[@placeholder='Nhập tên sản phẩm']";
    public static final String SELLING_PRICE_FIELD = "//input[@placeholder='Nhập giá bán']";
    public static final String IMPORT_PRICE_FIELD = "//input[@placeholder='Nhập giá nhập']";
    public static final String QUANTITY_FIELD = "//input[@placeholder='Nhập số lượng']";
    public static final String QUANTITY_TITLE = "//label[contains(text(),'Số lượng')]";
    public static final String SELECT_BRAND_DROPDOWN_LIST_PARENT = "//input[@placeholder='Chọn thương hiệu']";
    public static final String BRAND_NAME = "//p[text()='Thương hiệu']/following-sibling::div/div[2]/div[1]";
    public static final String SELECT_PRODUCT_CATEGORY_LIST_PARENT = "//input[@placeholder='Chọn ngành hàng']";
    public static final String SELECT_PRODUCT_GROUP_LIST_PARENT = "//input[@placeholder='Chọn nhóm sản phẩm']";
    public static final String ENABLE_STATUS_BUTTON = "//p[text()='Trạng thái']/parent::div/div";
    public static final String SELL_ONLINE_BUTTON = "//p[text()='Bán online']/../div/label/div";
    public static final String PRODUCT_DESCRIPTION_FIELD = "//textarea[@placeholder='Nhập mô tả']";
    public static final String SAVE_BUTTON = "//button[text()='Lưu']";
    public static final String PRODUCT_CATEGORY_NAME = "//p[text()='Ngành hàng']/following-sibling::div/div[2]/div[1]";
    public static final String PRODUCT_GROUP_NAME = "//p[text()='Nhóm sản phẩm']/following-sibling::div/div[2]/div[1]";
    public static final String PRODUCT_IMAGE = "//input[@type='file']";
    public static final String PRODUCT_NAME_TEXT_IN_DETAIL_PAGE = "//p[@class='mb-2 font-medium text-base break-all']";
    public static final String BAR_CODE_TEXT_IN_DETAIL_PAGE = "//p[text()='Mã vạch']/following-sibling::p";
    public static final String SELLING_PRICE_TEXT_IN_DETAIL_PAGE = "//p[text()='Giá bán']/following-sibling::p";
    public static final String IMPORT_PRICE_TEXT_IN_DETAIL_PAGE = "//p[text()='Giá nhập']/following-sibling::p";
    public static final String BRAND_NAME_TEXT_IN_DETAIL_PAGE = "//p[text()='Thương hiệu']/following-sibling::p";
    public static final String PRODUCT_CATEGORY_NAME_TEXT_IN_DETAIL_PAGE = "//p[text()='Ngành hàng']/following-sibling::p";
    public static final String PRODUCT_GROUP_NAME_TEXT_IN_DETAIL_PAGE = "//p[text()='Nhóm sản phẩm']/following-sibling::p";
    public static final String PRODUCT_BAR_CODE_TEXT_IN_DETAIL_PAGE = "//p[text()='Mã vạch']/following-sibling::p";
    public static final String PRODUCT_DESCRIPTION_TEXT_IN_DETAIL_PAGE = "//div[@class='bg-white flex justify-between items-center rounded-lg p-5 mt-4 grid-cols-1 gap-4']/div/p";
    public static final String BRAND_NAME_TEXT = "//div[@class='w-full bg-white overflow-y-auto max-h-[300px] border border-gray-light rounded-lg']/div[1]/div";
    public static final String PRODUCT_CATEGORY_NAME_TEXT = "//div[@class='w-full bg-white overflow-y-auto max-h-[300px] border border-gray-light rounded-lg']/div[1]/div";
    public static final String PRODUCT_GROUP_NAME_TEXT = "//div[@class='w-full bg-white overflow-y-auto max-h-[300px] border border-gray-light rounded-lg']/div[1]/div";
    public static final String PRODUCT_STATUS_IN_DETAIL_PAGE = "//div[@class='flex items-center']/p";
    public static final String SELL_ONLINE_STATUS_IN_DETAIL_PAGE = "//p[text()='Bán online']/following-sibling::p";
    public static final String DEFAULT_VARIANT_NAME = "//input[@placeholder='Nhập tên sản phẩm']/following-sibling::span";
    public static final String DEFAULT_VARIANT_BARCODE = "//input[@placeholder='Nhập hoặc quét mã vạch']/following-sibling::span";
    public static final String DEFAULT_VARIANT_IMPORT_PRICE = "//div[@class='flex items-center justify-between gap-4']//div/label/following-sibling::div/input[@placeholder='Nhập giá nhập']/following-sibling::span";
    public static final String DEFAULT_VARIANT_SELL_PRICE = "//div[@class='flex items-center justify-between gap-4']//div/label/following-sibling::div/input[@placeholder='Nhập giá bán lẻ']/following-sibling::span";
    public static final String ADD_VARIANT_BUTTON = "//button[contains(text(),'Thêm thuộc tính')]";
    public static final String MARK_POINT_TO_SCROLL = "//p[text()='Thuộc tính']";
    public static final String FIRST_PROPERTY_NAME_FIELD = "//input[@placeholder='Nhập tên thuộc tính']";
    public static final String FIRST_PROPERTY_VALUE_FIELD = "//input[@placeholder='Nhập giá trị thuộc tính...']";
    public static final String MARK_POINT_TO_CREATE_VARIANT = "//p[text()='Mẫu mã']";
    public static final String FIRST_VARIANT_NAME = "//p[text()='Tối đa 1 ảnh']/parent::div/preceding::label[1]/parent::div/parent::div/following-sibling::div[1]//span";
    public static final String FIRST_VARIANT_BARCODE_FIELD = "//p[text()='Tối đa 1 ảnh']/parent::div/preceding::label[1]/parent::div/parent::div/following-sibling::div[1]/following-sibling::div//label[contains(text(),'Mã vạch')]/following-sibling::div/input";
    public static final String FIRST_VARIANT_QUANTITY = "//p[text()='Tối đa 1 ảnh']/parent::div/preceding::label[1]/parent::div/parent::div/following-sibling::div[4]/div/input";
}
